### ISSUE TITLE
Models, Digest and ApoE example not in agreement

### ISSUE THREAD

**Issue by julesjacobsen** [ga4gh/vmc#11]
[models.py](https://github.com/ga4gh/vmc/blob/dev/demos/python/vmcdemo/app/models.py) doesn't appear to be the same as what was used for the [ApoE Example.ipynb](https://github.com/ga4gh/vmc/blob/dev/demos/python/notebooks/ApoE%20Example.ipynb)

for example there is no ```models.Vmcbundle``` and the ```computed_identifier``` returns different results:
```python
def computed_identifier(self):
        return "GL:" + self.digest() 
```
in the notebook the computed identifier is like this:

```
"VMC:GL_9Jht-lguk_jnBvG-wLJbjmBw5v_v7rQo"
```

which is computed from [digest.py](https://github.com/ga4gh/vmc/blob/dev/demos/python/vmcdemo/digest.py#L66)

```python
def computed_identifier(o):

    """return the VMC computed identifier for the object, as an Identifier
    """

    pfx = vmc_model_prefixes[type(o)]
    dig = truncated_digest(o)
    accession = "{pfx}_{dig}".format(pfx=pfx, dig=dig)
    return models.Identifier(namespace=vmc_namespace, accession=accession)
``` 

Which is the correct version? I'm assuming the ApoE example is the correct representation?

**Comment by reece** [comment]
@julesjacobsen -

First, I'm very sorry for the long delay. I had an extended vacation followed by, well, the return from vacation. I am thrilled that you're scrutinizing the code and will appreciate your feedback.

1) The computed_identifier with the hardcoded "GL" (from vmcdemo.app.models.py) is from early prototyping and I apologize for leaving that decoy around. The digest.py version is the current version.

2) Regarding VMCBundle, the models definitions are built at run time using code in vmcdemo._models.py. I did it this way because I wanted there to be a single authoritative source of models (as opposed to having to keep the json schema and python models in sync manually). _models.py generates the models in a dictionary called models. The intended way to get these models is `from vmcdemo import models` (which imports the models *dictionary*, not a models module).

You may also find some differences in key lengths between demo versions. (Obviously, this will be fixed when the proposal is finalized.)

I'll be making some additional changes over the next week. You may want to repull.

Please close if this answered your question.

**Comment by julesjacobsen** [comment]
No problem in the delay, thanks for the explanation. Could I also invite you to do a review of [my implementation](https://github.com/julesjacobsen/vmc-kotlin) - we need a JVM compatible library for this.
